% Y_1 - Y_2，把持力，物体角度グラフ
figure('Name', 'Y_1 - Y_2', 'NumberTitle', 'off', 'Position',[500 0 800 1500]);
subplot(3,1,1);
Y_d = plot(Y_theta(:,1), Y_theta(:,3), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
Y = plot(Y_theta(:,1), Y_theta(:,2), 'r', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
%legend([Y], '{\itY_1 - Y_2}',0);
xlabel('Time [s]');
ylabel('{\itY_1 - Y_2} [mm]');
axis([0,9,-5,10]);
% axis square;
grid on;

subplot(3,1,2);
f_d = plot(Y_theta(:,1), Y_theta(:,8), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
f_1 = plot(Y_theta(:,1), Y_theta(:,6), 'r', 'Linewidth', 1.5);
f_2 = plot(Y_theta(:,1), Y_theta(:,7), 'b', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
legend([f_1, f_2, f_d], '{\itf_1}', '{\itf_2}', '{\itf_d}', 4); 
xlabel('Time [s]');
ylabel('Pinchig force  {\itf_i} [N]');
axis([0,9,0,4]);
% axis square;
grid on;

subplot(3,1,3);
lambda_d = plot(Y_theta(:,1), Y_theta(:,11), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
lambda_1 = plot(Y_theta(:,1), Y_theta(:,9), 'r', 'Linewidth', 1.5);
lambda_2 = plot(Y_theta(:,1), Y_theta(:,10), 'b', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
legend([lambda_1, lambda_2], '{\it\lambda_1}','{\it\lambda_2}', 4); 
xlabel('Time [s]');
ylabel('Rolling constraint force  {\it\lambda_i} [N]');
axis([0,9,-0.5,1]);
% axis square;
grid on;

figure('Name', 'The position of an object', 'NumberTitle', 'off', 'Position',[500 0 800 1500]);
subplot(3,1,1);
x_d = plot(Y_theta(:,1), Y_theta(:,12), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
x = plot(Y_theta(:,1), Y_theta(:,14), 'r', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
legend([x_d, x], '{\itx_d}', '{\itx}', 4); 
xlabel('Time [s]');
ylabel('Object  {\itx}-position [m]');
axis([0,9,0.04,0.08]);
% axis square;
grid on;

subplot(3,1,2);
y_d = plot(Y_theta(:,1), Y_theta(:,13), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
y = plot(Y_theta(:,1), Y_theta(:,15), 'r', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
legend([y_d, y], '{\ity_d}', '{\ity}', 4); 
xlabel('Time [s]');
ylabel('Object  {\ity}-position [m]');
axis([0,9,0.07,0.12]);
% axis square;
grid on;

subplot(3,1,3);
theta_d = plot(Y_theta(:,1), Y_theta(:,5), ':g', 'Color', [0.000 0.800 0.500], 'Linewidth', 1.5);
hold on;
theta = plot(Y_theta(:,1), Y_theta(:,4), 'r', 'Linewidth', 1.5);
set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times', 'xtick', [0 2 4 6 8]);
% set(gca, 'FontWeight', 'normal', 'FontSize', 15, 'FontName', 'times');
legend([theta_d, theta], '{\it\theta}', '{\it\theta_d}', 4); 
xlabel('Time [s]');
ylabel('Object angle  {\it\theta} [rad]');
axis([0,9,-5,15]);
% axis square;
grid on;
